### ISSUE TITLE
Unable to auth to intersight with api key (http 401)

### ISSUE THREAD

**Issue by mynamewastaken** [CiscoUcs/intersight-ansible#43]
I'm unable to auth to https://intersight.com/api/v1 even with a very minimal playbook. This is running inside the top level directory of intersight-ansible:
```
- hosts: localhost
  connection: local
  tasks:
    - name: test
      intersight_rest_api:
        api_private_key: 'file_location'
        api_key_id: 'my_id'
        api_uri: 'https://intersight.com/api/v1'
        resource_path: /iam/Users
```
This returns http 401.

However, I am able to auth with the same public/private key and api_uri using https://github.com/CiscoUcs/intersight-python and a test script:
```
from intersight.apis import iam_user_api
api_instance = IntersightApiClient(host=api_uri, api_key_id=api_key_id, private_key=api_private_key)

users_handle = iam_user_api.IamUserApi(api_instance)
print users_handle.iam_users_get()
```

This returns the list of users with full details. Any ideas on how to troubleshoot this further?
